// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE8UYxc1zP_t-6u5oCWgS8mi_jM5EAICs',
    appId: '1:972396664960:web:2279e76bc8c8f04fc7ee65',
    messagingSenderId: '972396664960',
    projectId: 'appexlove-e7972',
    authDomain: 'appexlove-e7972.firebaseapp.com',
    storageBucket: 'appexlove-e7972.appspot.com',
    measurementId: 'G-2XXW7K7PF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdhu31nFWneuo6-oEkadtgqViRbHQLevI',
    appId: '1:972396664960:android:b25e40942b206391c7ee65',
    messagingSenderId: '972396664960',
    projectId: 'appexlove-e7972',
    storageBucket: 'appexlove-e7972.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOj3xj7vLOaZ2j16uTs-6mCP3BI_F9rnU',
    appId: '1:972396664960:ios:6b93548e8ab42f2bc7ee65',
    messagingSenderId: '972396664960',
    projectId: 'appexlove-e7972',
    storageBucket: 'appexlove-e7972.appspot.com',
    iosBundleId: 'com.example.datingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOj3xj7vLOaZ2j16uTs-6mCP3BI_F9rnU',
    appId: '1:972396664960:ios:6b93548e8ab42f2bc7ee65',
    messagingSenderId: '972396664960',
    projectId: 'appexlove-e7972',
    storageBucket: 'appexlove-e7972.appspot.com',
    iosBundleId: 'com.example.datingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE8UYxc1zP_t-6u5oCWgS8mi_jM5EAICs',
    appId: '1:972396664960:web:bda12ccf1cc6fae9c7ee65',
    messagingSenderId: '972396664960',
    projectId: 'appexlove-e7972',
    authDomain: 'appexlove-e7972.firebaseapp.com',
    storageBucket: 'appexlove-e7972.appspot.com',
    measurementId: 'G-2Y617P5900',
  );
}
